### ISSUE TITLE
Problem na WooCommerce 3.4.0

### ISSUE THREAD

**Issue by sklepVoIP** [piotr-urbanowicz/woo-payments-by-shipping#4]
Rewelacyjna wtyczka, ale niestety po aktualizacji WooCommerce do wersji 3.4.0 pojawiły się poważne problemy. Co zauważyłem:
- nie ma możliwości edycji zamówień
- nie otwiera się strona WooCommerce \ Ustawienia (błąd 500)

Czy dałoby się to w jakiś sposób naprawić? Byłbym wdzięczny za pomoc.

**Comment by abclution** [comment]
[Tue May 29 17:48:23.370115 2018] [fcgid:warn] [pid 13703]  mod_fcgid: stderr: #1 /home/shop/www/wp-includes/plugin.php(203): WP_Hook->apply_filters(Array, Array), referer: https://www.shop.eu/wp-admin/plugins.php
[Tue May 29 17:48:23.370123 2018] [fcgid:warn] [pid 13703]  mod_fcgid: stderr: #2 /home/shop/www/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-shipping-method.php(498): apply_filters('woocommerce_shi...', Array), referer: https://www.shop.eu/wp-admin/plugins.php
[Tue May 29 17:48:23.370131 2018] [fcgid:warn] [pid 13703]  mod_fcgid: stderr: #3 /home/shop/www/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-shipping-method.php(457): WC_Shipping_Method->get_instance_form_fields(), referer: https://www.shop.eu/wp-admin/plugins.php
[Tue May 29 17:48:23.370139 2018] [fcgid:warn] [pid 13703]  mod_fcgid: stderr: #4 /home/shop/www/wp-content/plugins/woocommerce/includes/shipping/local-pickup/class-wc-shipping-local-pickup.php(51): WC_Shipping_Method->get_option('title'), referer: https://www.shop.eu/wp-admin/plugins.php
[Tue May 29 17:48:23.370148 2018] [fcgid:warn] [pid 13703]  mod_fcgid: stderr: #5 /home/shop/www/wp-content/plugins/woocommerce/includes/shipping/local-pickup/class-wc-shipping-l in /home/shop/www/wp-content/plugins/woo-payments-by-shipping/includes/class-woo-payments-by-shipping.php on line 28, referer: https://www.shop.eu/wp-admin/plugins.php

**Comment by s4ndr0wy** [comment]
Hi,
I have the same problem. I cannot access to WooCommerce Settings. This is the error message:

`Fatal error: Uncaught Error: Call to a member function payment_gateways() on null in /domains/zaczarowanetorebki.pl/public_html/wp-content/plugins/woo-payments-by-shipping-master/includes/class-woo-payments-by-shipping.php:28 Stack trace: #0 /domains/zaczarowanetorebki.pl/public_html/wp-includes/class-wp-hook.php(286): Woo_Payments_By_Shipping->woo_payments_by_shipping_add_settings(Array) #1 /domains/zaczarowanetorebki.pl/public_html/wp-includes/plugin.php(203): WP_Hook->apply_filters(Array, Array) #2 /domains/zaczarowanetorebki.pl/public_html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-shipping-method.php(498): apply_filters('woocommerce_shi...', Array) #3 /domains/zaczarowanetorebki.pl/public_html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-shipping-method.php(457): WC_Shipping_Method->get_instance_form_fields() #4 /domains/zaczarowanetorebki.pl/public_html/wp-content/plugins/woocommerce/includes/shipping/flat-rate/includes/settings-flat-rate.php(61): WC_Shipping_Method->get_option('c in /domains/zaczarowanetorebki.pl/public_html/wp-content/plugins/woo-payments-by-shipping-master/includes/class-woo-payments-by-shipping.php on line 28`

And error in Order detail:
`Fatal error: Uncaught Error: Call to a member function payment_gateways() on null in /domains/zaczarowanetorebki.pl/public_html/wp-content/plugins/woo-payments-by-shipping-master/includes/class-woo-payments-by-shipping.php:28 Stack trace: #0 /domains/zaczarowanetorebki.pl/public_html/wp-includes/class-wp-hook.php(286): Woo_Payments_By_Shipping->woo_payments_by_shipping_add_settings(Array) #1 /domains/zaczarowanetorebki.pl/public_html/wp-includes/plugin.php(203): WP_Hook->apply_filters(Array, Array) #2 /domains/zaczarowanetorebki.pl/public_html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-shipping-method.php(498): apply_filters('woocommerce_shi...', Array) #3 /domains/zaczarowanetorebki.pl/public_html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-shipping-method.php(457): WC_Shipping_Method->get_instance_form_fields() #4 /domains/zaczarowanetorebki.pl/public_html/wp-content/plugins/woocommerce/includes/shipping/flat-rate/includes/settings-flat-rate.php(61): WC_Shipping_Method->get_option('c in /domains/zaczarowanetorebki.pl/public_html/wp-content/plugins/woo-payments-by-shipping-master/includes/class-woo-payments-by-shipping.php on line 28`


Can we get a quick fix of this issue?

**Comment by piotr-urbanowicz** [comment]
Sorry guys, I'm really busy right now, but I'll try to fix that within few days. Be patient, please.

**Comment by sklepVoIP** [comment]
Great, I am waiting impatiently for the fix. This plugin is really good!

**Comment by journalist1980** [comment]
Hi, any update?

**Comment by journalist1980** [comment]
No?

**Comment by journalist1980** [comment]
Solved this problem by buying from woocommerce.com the conditional plugin. They have 50% off until the 17th midnight ($40) better to have something than nothing.

**Comment by piotr-urbanowicz** [comment]
It's been a while, but I've fixed the plugin. It is supported on WooCommerce 3.4.0 and upper versions.
